export const Questions = [
    { id: 1, Ques: 'Email', short: 'email',des:''},
    { id: 2, Ques: 'Full Name',short: 'f_Name',des:''},
    { id: 3, Ques: 'Age', short: 'age',des:''},
    { id: 4, Ques: 'Highest Level of Education',short: 'high_Education' ,des:''},
    { id: 6, Ques: 'Institute where you completed your highest level of education' ,short: 'completeHigh_Education',des:'' },
    { id: 7, Ques: 'What did you study',short: 'studyField',des:''},
    { id: 8, Ques: 'Do you have any relevant work experience?' ,short: 'workExp' ,des:'Write None if no work experience. Provide the following details if yes:'},
    { id: 9, Ques: 'What institute did you get admitted to in Canada?'  ,short: 'Canada_Inst' ,des:''},
    { id: 10, Ques: 'What is your program of study in Canada?' ,short: 'CanadaStudy',des:'' },
    { id: 11, Ques: 'Which country are you applying from?'  ,short: 'applyCountry',des:''},
    { id: 12, Ques: 'What are your future goals?' ,short: 'futureGoal' ,des:''},
    { id: 13, Ques: 'English Scores - Listening' ,short: 'listining' ,des:''},
    { id: 14, Ques: 'English Scores - Reading',short: 'reading' ,des:''},
    { id: 15, Ques: 'English Scores - Speaking' ,short: 'speaking',des:''},
    { id: 16, Ques: 'English Scores - Writing',short: 'writing',des:'' },
    { id: 17, Ques: 'Did you pay your first year tuition?',short: 'payTuitionFee',des:'' },
    { id: 18, Ques: 'How much tuition fee did you pay?',short: 'tuitionfeeAmount' ,des:''},
    { id: 19, Ques: 'Did you do a GIC?' ,short: 'doGIC',des:'' },
    { id: 20, Ques: 'How much did you pay towards GIC?' ,short: 'GIC_Amount',des:''},
]